# Generated by Django 4.0.1 on 2022-02-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='summarized_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
